### ISSUE TITLE
Question about joint control and action process

### ISSUE THREAD

**Issue by LeiHHHuang** [yzqin/dexmv-sim#1]
Hi Yuzhe, thank you for open-sourcing this amazing project! I successfully made the examples run under your comprehensive instructions but have a few detailed questions. 

1. When I step the MujocoEnv with a handcraft action and print the state, there are always some offsets (some of them are in the magnitude of 0.1) between the action and the stabilized state, I was wondering if this situation is normal? 
2. When I set the hand to move along the z-axis for a small distance, the hand swings along that axis a bit before it stabilizes in the expected location (I noticed that the demo videos also have this phenomenon), is this expected due to the inertia of the hand and are there any ways to avoid this? 

Thank you very much in advance!

**Comment by yzqin** [comment]
Hi @LeiHHHuang ,

Thanks for your interest in our code. 

1. The short answer is yes, this is a normal behavior. DexMV utilized the action space from the [dapg repo](https://github.com/vikashplus/mj_envs), the action is defined as the position control in MuJoCo. However, this position control is not infinity stiff, so that it can not reach the specified position target (handcraft action) perfectly, especially for the transnational axis aligns with gravity. You can refer to the [MuJoCo position actuator](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-position) for more details about this implementation.

2. This behavior is originates from this same reason as above. The position actuator in MuJoCo is a P controller, it needs some time to converge to the specified target. To avoid this (in principal you can not avoid it but alleviate it), you can increase the parameters to reduce the swings duration. 
Chane the parameters [here](https://github.com/yzqin/dexmv-sim/blob/master/hand_imitation/env/models/assets/adroit/adroit_relocate.xml#L439-L463) if you are using the relocate env:

500 -> -5000 in the `gainprm` (you may need to tune parameter based on the behavior)

**Comment by yzqin** [comment]
Hi @LeiHHHuang, did you get a chance to go through the above comment. Thanks!

**Comment by LeiHHHuang** [comment]
Hi @yzqin , thank you so much for the circumstantial explanation! It is really helpful : )
