### ISSUE TITLE
Some import errors in examples/train.py

### ISSUE THREAD

**Issue by mars747** [yzqin/dexmv-sim#4]
Hi,

Thanks for your great work!

I think there are some typos in the imports in examples/train.py

In line 15,
https://github.com/yzqin/dexmv-sim/blob/a7508f07de07f3643719e9c42b9cb5eac2e5802d/examples/train.py#L15
is the file supposed to be mjrl.algos.behavior_cloning instead of mjrl.algos.behavior_cloning_2?

in line 17,
from mjrl.algos.density_onpg, the file doesn't exist. 

Is the dexmv-learn repo out of sync?

Thanks!

**Comment by yzqin** [comment]
Hi @mars747,

Thanks for pointing that out! I apologize for the version mismatch between these two repos.

This issue should be fixed in the recent commit ed32fc872b44ae925e4bbb19638bf3767230479d of `dexmv-sim` repo and commit yzqin/dexmv-learn@272d907f318983bb72ed29a0e06bdfec17b07266 of `dexmv-learn` repo.

Regards!

**Comment by mars747** [comment]
That's great. Thanks!
