### ISSUE TITLE
YCB object file format

### ISSUE THREAD

**Issue by LeiHHHuang** [yzqin/dexmv-sim#8]
Hi Yuzhe! 
I am trying to add other YCB objects that are not included in the assets under hand_imitation directory. The YCB objects downloaded from _http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/_ come with formats such as `.stl`, `.dae`, `.obj`, and `.mtl`, but in the visual directory, the file formats are `.msh`. I am wondering how you got the .msh files? I have tried to convert other formats to .msh using meshio but turned out not working... 

Thanks in advance!

**Comment by yzqin** [comment]
Hi @LeiHHHuang ,

Thanks for your interest. The `msh` is not a common mesh format. We use it just because MuJoCo only support `stl` (no texture) and `msh` (has texture) when we develop this project. MuJoCo begin to support obj from late 2022, maybe you can modify the code little bit and use the obj file from YCB to add more objects.

The `msh` in this repo are converted from obj using some small tools like [this one](https://github.com/daeyun/obj2mesh). You can take a look if you want to use the same MuJoCo version as DexMV rather upgrade to the latest MuJoCo.

By the way, we give using MuJoCo for simulation for now due to the heavy penetration and migrate to [SAPIEN](https://sapien.ucsd.edu/).

**Comment by LeiHHHuang** [comment]
This is very helpful. I will check out SAPIEN as well. Thank you so much!
